SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS;

ALTER TABLE ACTOR ADD CONSTRAINT PK_ACTORID PRIMARY KEY (actor_id);
ALTER TABLE category ADD CONSTRAINT PK_CATEGORYID PRIMARY KEY (category_id);
ALTER TABLE ACTOR MODIFY first_name CONSTRAINT CK_FNAME NOT NULL;
ALTER TABLE ACTOR MODIFY last_name CONSTRAINT CK_LNAME NOT NULL;
ALTER TABLE FILM MODIFY film_title CONSTRAINT CK_TILE NOT NULL;
ALTER TABLE CATEGORY  MODIFY name CONSTRAINT CK_CATANAME NOT NULL;
ALTER TABLE FILM  MODIFY rental_rate CONSTRAINT CK_RENTALRATE NOT NULL;
ALTER TABLE FILM ADD CONSTRAINT CK_RATING CHECK ((rating = 'G') OR (rating = 'PG') OR (rating = 'PG-13') OR (rating = 'R') OR (rating = 'NC-17'));
ALTER TABLE FILM ADD CONSTRAINT CK_SPLFEATURES CHECK ((SPECIAL_FEATURES IS NULL) OR (SPECIAL_FEATURES = 'Trailers') OR (SPECIAL_FEATURES = 'Commentaries') OR (SPECIAL_FEATURES = 'Deleted Scenes') OR (SPECIAL_FEATURES = '''Behind the
Scenes'));
ALTER TABLE FILM ADD CONSTRAINT FK_LANGUAGE FOREIGN KEY (language_id) REFERENCES language (language_id);
ALTER TABLE FILM ADD CONSTRAINT FK_ORLANGUAGEID FOREIGN KEY (original_language_id ) REFERENCES language (language_id);
ALTER TABLE FILM_ACTOR ADD CONSTRAINT FK_ACTORID FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR (ACTOR_ID);
ALTER TABLE FILM ADD CONSTRAINT CK_RELEASEYR CHECK (RELEASE_YEAR <= 2018);

CREATE SEQUENCE "FILM_ID_SEQ" MINVALUE 2020 INCREMENT BY 2 START WITH 22000;

CREATE OR REPLACE TRIGGER "BI_FILM_ID"
  BEFORE INSERT ON "FILM"
  FOR EACH ROW
BEGIN
    SELECT "FILM_ID_SEQ".nextval INTO :NEW.FILM_ID FROM DUAL;
END;
  /

SHOW ERRORS;